apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  namespace: nepremicnine
spec:
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: potocnikvid/nepremicnine-authentication
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SUPABASE_SERVICE_ROLE_KEY
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SUPABASE_URL
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SUPABASE_KEY
            - name: SUPABASE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SUPABASE_JWT_SECRET
            - name: AUTHENTICATION_SERVER_MODE
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AUTHENTICATION_SERVER_MODE
            - name: AUTHENTICATION_SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AUTHENTICATION_SERVER_PORT
          resources:
            limits:
              cpu: "0.1"
              memory: "256Mi"
            requests:
              cpu: "0.01"
              memory: "32Mi"
          readinessProbe:
            httpGet:
              path: /authentication/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
            successThreshold: 10
            failureThreshold: 30
          livenessProbe: null
            httpGet:
              path: /authentication/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10