apiVersion: v1
kind: Service
metadata:
  name: authentication
  namespace: nepremicnine
  labels:
    app: authentication
spec:
  type: ClusterIP
  selector:
    app: authentication
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080